In [1]:
import numpy as np

In [2]:
w_1 = np.matrix('0.1 -0.5; -0.3 -0.9; 0.8 0.02')
w_1

matrix([[ 0.1 , -0.5 ],
        [-0.3 , -0.9 ],
        [ 0.8 ,  0.02]])

In [3]:
w_2 = np.array([-0.4, 0.2, -0.5])
w_2

array([-0.4,  0.2, -0.5])

In [4]:
b_1 = np.array([[0.1, 0.5, 0.8 ]]).T
b_1

array([[0.1],
       [0.5],
       [0.8]])

In [5]:
b_2 = 0.7
b_2

0.7

In [6]:
x = np.array([[1.8, -3.4]]).T
x


array([[ 1.8],
       [-3.4]])

In [7]:
#Calculamos z = (w.x + b)
z_1 = np.dot(w_1,x)+b_1
z_1

matrix([[1.98 ],
        [3.02 ],
        [2.172]])

In [8]:
#Calculamos y1 = sigma(z)
y1 = 1/(1+np.exp(-z_1))
y1

matrix([[0.87868116],
        [0.95346953],
        [0.89770677]])

In [9]:
#Calculamos g'(z) = (exp(z)/[1+exp(-z)]^2)
a = 1+np.exp(-z_1)
g_derivada = np.exp(z_1)/np.power(a,2)
g_derivada

matrix([[ 5.59198124],
        [18.62871802],
        [ 7.07223392]])

In [10]:
#Calculamos dY = dJ/dy_hat
dY_1 = y1-5
dY_1

matrix([[-4.12131884],
        [-4.04653047],
        [-4.10229323]])

<h4>Cálculo dJ/dW1 - dJ/db1</ha>

<h4></h4>

In [11]:
#Calculamos dJ/dW1 = (y1-5).g'(z).x_t
dJ_dW1 = np.multiply((dY_1), g_derivada)@x.T
print(f'La derivada de J respecto a w1 es:\n', dJ_dW1)

La derivada de J respecto a w1 es:
 [[ -41.48340771   78.3575479 ]
 [-135.68701532  256.29769561]
 [ -52.22227917   98.64208287]]


In [12]:
#Calculamos dJ_db1 = dY.g'(z)
dJ_db1 = np.multiply(dY_1, g_derivada)
print(f'La derivada de J respecto a b1 es:\n', dJ_db1)


La derivada de J respecto a b1 es:
 [[-23.04633762]
 [-75.38167518]
 [-29.01237731]]


<h4>Cálculo dJ/dW2 - dJ/b2<h4>

In [13]:
#Calculamos z_2 = (w.y1 + b)
z_2 = (w_2*y1)+b_2
z_2

matrix([[0.09036805]])

In [14]:
#Calculamos y2 = sigma(z)
y2 = 1/(1+np.exp(-z_2))
y2

matrix([[0.52257665]])

In [15]:
#Calculamos g'(z) = (exp(z)/[1+exp(-z)]^2)
a2 = 1+np.exp(-z_2)
g2_derivada = np.exp(z_2)/np.power(a2,2)
g2_derivada

matrix([[0.29891407]])

In [21]:
#Calculamos dY2 = dJ/dy_hat
dY_2 = y2-5
dY_2

matrix([[-4.47742335]])

In [17]:
#Calculamos dJ/dW2 = dY_2.g'(z).x_t
dJ_dW2 = np.multiply((dY_2), g2_derivada)@y1.T
print(f'La derivada de J respecto a w2 es:\n', dJ_dW2)

La derivada de J respecto a w2 es:
 [[-1.17599595 -1.27609007 -1.20145916]]


In [18]:
#Calculamos dJ_db2 = dY_2.g'(z). 
#np.multiply permite aplicar producto de Hadamard
dJ_db2 = np.multiply(dY_2, g2_derivada)
print(f'La derivada de J respecto a b1 es:\n', dJ_db1)

La derivada de J respecto a b1 es:
 [[-23.04633762]
 [-75.38167518]
 [-29.01237731]]
